package modelo;

public class Persistencia 
{
    public static String [] InteresC = {"1 ¿Aceptarías trabajar escribiendo artículos en la sección económica de un diario?","12 ¿Puedes establecer la diferencia conceptual entre macroeconomía y microeconomía?","64 ¿Te gustaría realizar una investigación que contribuyera a hacer más justa la distribución de la riqueza?", "98 ¿Sabes qué es el PBI?","53 ¿Si una gran empresa solicita un profesional como gerente de	comercialización, te sentirías a gusto desempeñando ese rol?","85 ¿Te costearías tus estudios trabajando en una auditoría?","78 ¿Dirigirías el área de importación y exportación de una empresa?","20 ¿Si te convocara tu club preferido para planificar, organizar y dirigir un campo de deportes, aceptarías?","71 ¿En un equipo de trabajo, preferís el rol de coordinador?","91 ¿Te resultaría gratificante ser asesor contable en una empresa reconocida?"};
    public static String [] InteresH = {"9 ¿Te ofrecerías para explicar a tus compañeros un determinado tema que ellos no entendieron?","34 ¿Te interesan los temas relacionados al pasado y a la evolución del hombre?","80 ¿Te gratificaría el trabajar con niños?", "25 ¿Pasarías varias horas leyendo algún libro de tu interés?","95 ¿Dedicarías parte de tu tiempo a ayudar a personas de zonas carenciadas?","67 ¿La libertad y la justicia son valores fundamentales en tu vida?","41 ¿Participarías de una investigación sobre la violencia en el fútbol?","74 ¿Lucharías por una causa justa hasta las últimas consecuencias?","56 ¿Descubriste algún filósofo o escritor que haya expresado tus mismas ideas con antelación?","89 ¿Elegirías una carrera cuyo instrumento de trabajo fuere la utilización de un idioma extranjero?"};
    public static String [] InteresA = {"21 ¿Eres el que pone un toque de alegría en las fiestas?","45 ¿Tolerarías empezar tantas veces como fuere necesario hasta obtener el logro deseado?","96 ¿Cuando elegís tu ropa o decoras un ambiente, tienes en cuenta la combinación de los colores, las telas o el estilo de los muebles?", "57 ¿Desearías que te regalen algún instrumento musical para tu cumpleaños?","28 ¿Disfrutas modelando con arcilla?","11 ¿Te atrae armar rompecabezas o puzzles?","5 ¿Te dedicarías a socorrer a personas accidentadas o atacadas por asaltantes?","3 ¿Te gustaría dirigir un proyecto de urbanización en tu provincia?","81 ¿Harías el diseño de un afiche para una campaña contra el sida?","36 ¿Fuera de los horarios escolares, dedicas algún día de la semana a la realización de actividades corporales?"};
    public static String [] InteresS = {"33 ¿Participarías en una campaña de prevención contra la enfermedad de	Chagas?","92 ¿Ante un llamado solidario, te ofrecerías para cuidar a un enfermo?","70 ¿Te interesaría investigar sobre alguna nueva vacuna?", "8 ¿Escuchas atentamente los problemas que te plantean tus amigos?","87 ¿Ante una emergencia epidémica participarías en una campaña brindando tu	ayuda?","62 ¿Acostumbras a leer revistas relacionadas con los últimos avance s científicos y tecnológicos en el área de la salud?","23 ¿Te sentirías a gusto trabajando en un ámbito hospitalario?","44 ¿Te agradaría hacer un curso de primeros auxilios?","16 ¿Convences fácilmente a otras personas sobre la validez de tus argumentos?","52 ¿Te resultó interesante el estudio de las ciencias biológicas?"};
    public static String [] InteresI = {"75 ¿Te gustaría investigar científicamente sobre cultivos agrícolas?","6 ¿Cuando eras chico, te interesaba saber cómo estaban construidos tus juguetes?","19 ¿Cuando tienes que resolver un problema matemático, perseveras hasta encontrar la solución?", "38 ¿Te ofrecerías para colaborar como voluntario en los gabinetes espaciales de	la NASA?","60 ¿Cuando se descompone un artefacto en tu casa, te dispones prontamente a	repararlo?","27 ¿Entablas una relación casi personal con tu computadora?","83 ¿Enviarías tu currículum a una empresa automotriz que solicita gerente para su área de producción?","54 ¿Te incluirías en un proyecto nacional de desarrollo de la principal fuente de recursos de tu provincia?","47 ¿Harías un curso para aprender a fabricar los instrumentos y/o piezas de las máquinas o aparatos con que trabajas?","97 ¿Te gustaría trabajar como profesional dirigiendo la construcción de una	empresa hidroeléctrica?"};
    public static String [] InteresD = {"84 ¿Participarías en un grupo de defensa internacional dentro de alguna fuerza armada?","31 ¿Aceptarías que las mujeres formaran parte de las fuerzas armadas bajo las mismas normas que los hombres?","48 ¿Elegirías una profesión en la tuvieras que estar algunos meses alejado de tu familia, por ejemplo el marino?", "73 ¿Estás de acuerdo con la formación de un cuerpo de soldados profesionales?","5 ¿Te dedicarías a socorrer a personas accidentadas o atacadas por asaltantes?","65 ¿Te gustaría realizar tareas auxiliares en una nave, como por ejemplo izado y arriado de velas, pintura y conservación del casco, arreglo de averías,conservación de motores, etc?","14 ¿Participarías como profesional en un espectáculo de acrobacia aérea?","37 ¿Te interesan las actividades de mucha acción y de reacción rápida en situaciones imprevistas y de peligro?","58 ¿Aceptarías colaborar con el cumplimiento de las normas en lugares públicos?","24 ¿Te gustaría participar para mantener el orden ante grandes desórdenes y	cataclismos?"};
    public static String [] InteresE = {"77 ¿Visitarías un observatorio astronómico para conocer en acción e l funcionamiento de los aparatos?","42 ¿Te gustaría trabajar en un laboratorio mientras estudias?","88 ¿Sabrías responder que significa ADN y ARN?", "17 ¿Estás informado sobre los nuevos descubrimientos que se están realizando sobre la Teoría del Big-Bang?","93 ¿Te atrae investigar sobre los misterios del universo, por ejemplo los agujeros negros?","32 ¿Te gustaría crear nuevas técnicas para descubrir las patologías de algunas	enfermedades a través del microscopio?","68 ¿Aceptarías hacer una práctica rentada en una industria de productos	alimenticios en el sector de control de calidad?","49 ¿Te radicarías en una zona agrícola-ganadera para desarrollar tus actividades como profesional?","35 ¿Te incluirías en un proyecto de investigación de los movimientos sísmicos y	sus consecuencias?","61 ¿Formarías parte de un equipo de trabajo orientado a la preservación de laflora y la fauna en extinción?"};
    
    
    public static String [] AptitudesC = {"15 ¿Organizas tu dinero de manera que te alcance hasta el próximo cobro?","51 ¿Te resulta fácil coordinar un grupo de trabajo?","2 ¿Te ofrecerías para organizar la despedida de soltero de uno de tus amigos?", "46 ¿Distribuyes tus horarios del día adecuadamente para poder hacer todo lo planeado?"};
    public static String [] AptitudesH = {"63 ¿Preservar las raíces culturales de nuestro país, te parece importante y	necesario?","30 ¿Consideras importante que desde la escuela primaria se fomente la actitud crítica y la participación activa?","72 ¿En una discusión entre amigos, te ofreces como mediador?", "86 ¿Eres de los que defiendes causas perdidas?"};
    public static String [] AptitudesA = {"22 ¿Crees que los detalles son tan importantes como el todo?","39 ¿Te gusta más el trabajo manual que el trabajo intelectual?","76 ¿Harías un nuevo diseño de una prenda pasada de moda, ante una reunión imprevista?", "82 ¿Dirigirías un grupo de teatro independiente?"};
    public static String [] AptitudesS = {"69 ¿Consideras que la salud pública debe ser prioritaria, gratuita y eficiente para	todos?","40 ¿Estarías dispuesto a renunciar a un momento placentero para ofrecer tu servicio como profesional?","29 ¿Ayudas habitualmente a los no videntes a cruzar la calle?", "4 ¿A una frustración siempre opones un pensamiento positivo?"};
    public static String [] AptitudesI = {"26 ¿Planificas detalladamente tus trabajos antes de empezar?","59 ¿Crees que tus ideas son importantes, y haces todo lo posible para ponerlas	en práctica?","90 ¿Trabajar con objetos te resulta más gratificante que trabajar con personas?", "10 ¿Eres exigente y crítico con tu equipo de trabajo?"};
    public static String [] AptitudesD = {"13 ¿Usar uniforme te hace sentir distinto, importante?","66 ¿Crees que un país debe poseer la más alta tecnología armamentista, a cualquier precio?","18 ¿Ante una situación de emergencia actúas rápidamente?", "43 ¿Arriesgarías tu vida para salvar la vida de otro que no conoces?"};
    public static String [] AptitudesE = {"94 ¿El trabajo individual te resulta más rápido y efectivo que el trabajo grupal?","7 ¿Te interesan más los misterios de la naturaleza que los secretos de la	tecnología?","79 ¿Te inhibís al entrar a un lugar nuevo con gente desconocida?", "55 ¿Tenés interés por saber cuales son las causas que determinan ciertos fenómenos, aunque saberlo no altere tu vida?"};
    
    public static String [] CarrerasCI = { "Organizativo" , "Supervicion" , "orden" , "Analisis y sintesis" , "Colaboracion" , "Calculo" , "Liderazgo" , "Participacion activa" };
    public static String [] CarrerasCA = { "Persuasivo" , "Objetivo" , "Practico" , "Tolerante" , "Responsable" , "Ambicioso" , "Dinamico" , "Resolutivo"};
    public static String [] CarrerasHI = {"Precision verbal" , "Organizacion" , "Relacion de hechos" , "lingüistica" , "Orden" , "Justicia" , "El hombre analitico" };
    public static String [] CarrerasHA = {"Responsable" , "Justo" , "conciliador" , "Persuacivo" , "Sagaz" , "Imaginativo" , "Comprensivo" , "Estabilidad emocional"};
    public static String [] CarrerasAI = {"EStetico" , "Armonico" , "Manual" , "Visual" , "Auditivo" , "Observacion y analisis" , "Senso-perceptivo" };
    public static String [] CarrerasAA = {"sencible" , "imaginativo" , "Creativo" , "Detallista" , "Innovador" , "Intuitivo" , "Paciente" , "Espontaneo"};
    public static String [] CarrerasSI = {"Asistir" , "Investigativo" , "Precision" , "Senso-perceptivo" , "Analitico" , "Ayudar" , "Curar " , " Rehabilitar "};
    public static String [] CarrerasSA = {"Altruista" , "Solidario" , "Paciente" , "Comprensivo" , "Respetuoso" , "Persuasivo" , "Servicial" , "Observador"};
    public static String [] CarrerasII = {"Calculo" , "Cientifico" , "Manual" , "Exacto" , "Planificador" , "Organizador" , "Controlador" };
    public static String [] CarrerasIA = {"preciso" , "Practico" , "Critico" , "Analitico" , "Rigido" , "Racional" , "Independiente" };
    public static String [] CarrerasDI = {"Justicia" , "Equidad" , "Colaboracion" , "Espiritu de equipo" , "Liderazgo" , "Coordinacion" , "Destreza fisica" };
    public static String [] CarrerasDA=  {"Arriesgado" , "Solitario" , "Valiente" , "Agresivo" , "Persuacivo" , "Aventurero" , "Equilibrio psiquico" };
    public static String [] CarrerasEI = {"Investigacion" , "Orden" , "Organizacion" , "Analisis y Sintesis" , "Numerico" , "Clasificar" , "Precision" , "Exacto"};
    public static String [] CarrerasEA = {"Metodico" , "Analitico" , "Observador" , "Introvertido" , "Paciente" , "Seguro" , "Independiente" , "Intuitivo"};
    
	public Persistencia() 
	{
		
	}
}
